{
  return handleExceptionWithCause(exception,null,null,logException);
}
